### ISSUE TITLE
Library's peerDependencies

### ISSUE THREAD

**Issue by eranshmil** [ngxs-labs/entity-state#10]
```json
{
  "name": "entity-state",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@ngxs/store": "^3.3.0"
  }
}
```

There's a reason why not support angular 6 and older ngxs versions?

**Comment by JanMalch** [comment]
Had Angular 6 as a peer dependency until 940de87. Tests didn't run. Bumping the Angular version fixed it.
@ngxs/store dependency is a good point. How far down would you go, when it's running?

**Comment by eranshmil** [comment]
Did you figure out why it was failing and why the upgrade fixed that?
Maybe it can be solved other way.

About NGXS, my guess it will work no matter what, but in my opinion, it will be enough to support all 3.x versions. And of course, it needs to be checked.

**Comment by markwhitfeld** [comment]
Although it would be great to support all 3.x versions I think that it would be safe to assume that anyone using this library is probably just setting up or is happy to upgrade. Regarding the Angular 7 dependency I think that is important to investigate

**Comment by NarHakobyan** [comment]
test failure reason was Jasmin types version, I have fixed it and opened a PR https://github.com/ngxs-labs/entity-state/pull/11

**Comment by eranshmil** [comment]
Great! But you don't have to revert the main package.json, only the peerDependencies.

**Comment by NarHakobyan** [comment]
@eranshmil yes you are right, I have removed it :)

**Comment by JanMalch** [comment]
What's the usual (CI) procedure for testing support of dependency versions? I mean I can't just lower the version number without confirming that it works with both ng6 and ng7 in the integration test?

**Comment by NarHakobyan** [comment]
need to create separate tags and branches for each angular version, for example, 
entity-state@6 -> angular6
entity-state@7 -> angular7
and I think need to be maintained only last version

**Comment by eranshmil** [comment]
I guess this issue isn't relevant anymore.
