### ISSUE TITLE
Help request / question => how to get an entity by id?

### ISSUE THREAD

**Issue by philly-vanilly** [ngxs-labs/entity-state#100]
Hi guys. Many thanks for making this lib. I just want to ask: how are you supposed to get an entity by its ID? Have I missed the interface for that or is it not possible? I can only find the interface for getting the nth entity or all entities as an array.

But I want to associate multiple entities (forum-threads and posts) as a graph-relationship and do not want to filter an array for the id every time. I think others have this use-case too.

As far as I understand the implementation of Entity it is a simple JS object with keys and values, where the values are also kept as a sorted array. So (unless it is possible already) why not give read access to the key-value-object?

**Comment by JanMalch** [comment]
You could either set it is as the active id and select that entity or you take the `entitiesMap` and use RxJS' `map`.
Does that help?

**Comment by philly-vanilly** [comment]
> You could either set it is as the active id and select that entity or you take the `entitiesMap` and use RxJS' `map`.
> Does that help?

NGXS selector's don't allow dynamically filtering for an attribute, do they? So activeId is only for the case when you know the id at buildtime, no? But entitiesMap should do the trick (and probably be even less boilerplate when used in a pipe); I just didn't see it in the example project. Thanks :)

**Comment by JanMalch** [comment]
You would have to set the active ID with the `SetActive` action beforehand.

See

https://github.com/ngxs-labs/entity-state/blob/master/integration/app/app.component.ts#L30 (selecting the active entity)
https://github.com/ngxs-labs/entity-state/blob/master/integration/app/app.component.ts#L107-L109 (setting the active entity ID)

https://github.com/ngxs-labs/entity-state/blob/master/integration/app/app.component.html#L16 (setting the active entity ID)
https://github.com/ngxs-labs/entity-state/blob/master/integration/app/app.component.html#L30 (using the active entity selector)
