### ISSUE TITLE
Proposal: Entity state decorator

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/entity-state#15]
# Proposal

A kind of state decorator to implement a standardized CRUD action mutators and selectors for an entity collection.

The decorator would receive the action classes for create, update, destroy and would map them to internal methods, and would expose some selectors for retrieving one, many and all entities and maybe a helper for filters

```
export interface Student {
  name: string;
  grade: number;
}

@EntityState<Student>({
  name: 'students',
  actions: {
    create: [StudentAdd, StudentFullLoad],
    destroy: [StudentDelete]
  }, 
  defaults: {
    // Decorator injects automatically the collection (array) of entities, and so on ...
    selectedId: number,
  },
})
class StudentState {} 
```

# Actions

```
export class StudentAdd {
  static readonly type = '[Student] Add'
  constructor (public payload: Student) {}
}

export class StudentFullLoad {
  static readonly type = '[Student] Full Load'
  constructor (public payload: Student[]) {}
}

export class StudentDelete {
  static readonly type = '[Student] Delete'
  constructor (public id: number) {}
}
```

# Use of selectors

```
const all = this.store.select(StudentState.retrieveAll)
const one = this.store.select(StudentState.retrieve(5))
```

or 

```
const all = this.store.select(EntityState.retrieveAll<StudentState>)
const one = this.store.select(EntityState.retrieve<StudentState>(5))
```

I'm not sure if the current version of typescript could implement that... Any ideas will be welcome!

**Comment by splincode** [comment]
Moved from https://github.com/ngxs/store/issues/56

**Comment by JanMalch** [comment]
Added more selectors (84d6871bb0093225bcad638ceca9edac3d4ed4a9) based on this issue.

| Proposal | Implementation |
|--|--|
| `StudentState.retrieveAll` | `TodoState.entities` |
| `StudentState.retrieve(5)` | `TodoState.nthEntity(5)` |
| - | `TodoState.paginatedEntities(5, 0) // size, page` |
