### ISSUE TITLE
Behaviour of remove action

### ISSUE THREAD

**Issue by JanMalch** [ngxs-labs/entity-state#157]
Should the `remove` action remove all entities, if the payload is strictly `=== null` or should this functionality be moved to a separate `removeAll` action?

**Comment by markwhitfeld** [comment]
From https://github.com/ngxs-labs/entity-state/pull/159#discussion_r330486163
> I think that this is a bit dangerous to remove everything if the payload is null. I would have expected it to remove nothing if the payload was missing.
> Maybe we should have a separate `removeAll` so that the action is explicit?

**Comment by JanMalch** [comment]
@philly-vanilly @kuhnroyal @cblaettl Do you have any opinion / insight on this topic?

**Comment by cblaettl** [comment]
I have no idea why I was tagged here, but I'm agreeing with Mark.

**Comment by JanMalch** [comment]
Saw you participating in another thread and I figured you are already using this library and might have some insight

**Comment by JanMalch** [comment]
Working on it right now and will add a `removeAll` action.
Update has the same behaviour. Both use the [`EntitySelector`](https://github.com/ngxs-labs/entity-state/blob/master/src/lib/actions/type-alias.ts#L8). Should it be updated aswell?
