### ISSUE TITLE
Entity Adapter

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/entity-state#16]
A while back I prototyped something like John Papas NGRX-DATA, https://gist.github.com/amcdnl/cafd37bc9a99e2cd7653ebc023e06ffe#file-readme-md

Something we might want to think about one day.

I have created a LIB to be used as follows. I'm using it on mine.
projects:

**How to use:**
```typescript
export class UserStateModel extends NgxsEntityStateModel<UserModel> {}

@State<UserStateModel>({
  name: 'user',
  defaults: UserStateModel.InitialState()
})
export class UserState implements NgxsOnInit {}
```

**Methods  Available:**
`NgxsEntityAdapter.addAll( payload, ctx );`
`NgxsEntityAdapter.addOne( payload, ctx );`
`NgxsEntityAdapter.updateOne( payload, ctx );`
`NgxsEntityAdapter.removeOne( payload, ctx );`

 **NgxsEntityStateModel Class:**
```typescript
export class NgxsEntityStateModel<T> {
  public ids: string[];
  public entities: { [id: string]: T };
  public selected: T | null;
  public isLoading: boolean;

  static InitialState() {
    return {
      ids: [],
      entities: {},
      selected: null,
      isLoading: false
    };
  }
}
```

https://github.com/ngxs/store/issues/541#issuecomment-412874263

**Comment by JanMalch** [comment]
I notice the following differences:

|His proposal| `entity-state` equivalent |
|--|--|
| Different methods for different quantities | different quanitites are realized with different parameter types |
| `selected` | `active` |
| :x: | `error` state |
| `ids` field | :x: |

So I think the only relevant difference is the `ids` field, which is missing in the current implementation.
According to Redux Recipes it's used to indicate order.

>Arrays of IDs should be used to indicate ordering. >https://redux.js.org/recipes/structuringreducers/normalizingstateshape#designing-a-normalized-state

I close this issue in favor of #17
