### ISSUE TITLE
Syntax discussion

### ISSUE THREAD

**Issue by JanMalch** [ngxs-labs/entity-state#2]
Discuss and decide on one of the following syntax for dispatching actions:

```typescript
// 1. Misses new keyword but has type information for payload
this.store.dispatch(UpdateActive(TodoState, { done: true }));

// 2. Looks more like the usual ngxs way but no type information for payload
this.store.dispatch(new TodoState.updateActive({ done: true }));
```

Also consider: Should the action be upper or lowercase? Change order of parameters?

**Comment by odahcam** [comment]
I like the first with lowercase.

**Comment by splincode** [comment]
@markwhitfeld 

seems logical

```ts
this.store.dispatch(new TodoState.updateActive({ done: true }));
```

**Comment by markwhitfeld** [comment]
I also prefer the first option (with lowercase if it is an action creator).
The second option would make things bit confusing between selectors and actions in the exposed static  interface.

First prize though would be of defining actions using new. Something like this:
```TS
this.store.dispatch(new UpdateActive(TodoState, { done: true }));
```
This action could be defined something like this:
```TS
export class UpdateActive<T>{
  constructor(private target: Type<EntityState<T>>, public payload: Updater<T>) {
    return <any> generateActionObject('updateActive', target, payload); 
    // This return tricks the constructor into returning something else ;-)
  }
}
```

**Comment by JanMalch** [comment]
Well, thats .. interesting. If something like this is actually possible I could also create those as static classes on the `EntityState` so something like `new TodoState.UpdateActive({ done: true })` could be possible with full type information.

**Comment by markwhitfeld** [comment]
If it makes you feel less uncomfortable then you could view it as just a mechanism to create a public API to your dynamic action generator 👍 😉

**Comment by odahcam** [comment]
Github needs a fire reaction. 🔥 😆 

I liked this comment https://github.com/ngxs-labs/entity-state/issues/2#issuecomment-441398387 proposal, it seems to join all the ideas in one. Maybe it needs some work to be more friendly, but I like it.

**Comment by JanMalch** [comment]
What do you propose to make it more friendly? Or what do you consider unfriendly?
Every approach that looks somewhat nicer is in a static context and loses all type information.

**Comment by odahcam** [comment]
That's actually very interesting hehe, but I don't have any other suggestion I would like stand for at the moment, I'm already good with what we have. With experience we'll know what to improve.

**Comment by markwhitfeld** [comment]
``` TS
this.store.dispatch(new UpdateActive(TodoState, { done: true }));
```
I think that if we start with this then we can always add other convenient ways to express it later.
I would avoid adding anything other than selectors to the EntityState static members for now.
Once something is added it is difficult to take it back ;-)

**Comment by JanMalch** [comment]
Closing this as the syntax is set for now.
