### ISSUE TITLE
Make pagination feature optional

### ISSUE THREAD

**Issue by bitflut** [ngxs-labs/entity-state#210]
First of all thanks for the great work !

As pagination is very specific to every application, I'd suggest that this library should best not assume any kind of implementation. It'd be easier to add your own implementation than work around the provided one.

**Comment by splincode** [comment]
https://github.com/ngxs-labs/data/blob/master/docs/pages/entity.md

Yes, I also took this moment into account in the new plugin.

**Comment by bitflut** [comment]
Looks perfect!
