### ISSUE TITLE
Angular 9 upgrade blocked

### ISSUE THREAD

**Issue by dmitry-salnikov** [ngxs-labs/entity-state#222]
When upgrading to angular 9 the next incompatible peer dependency error appears:

```Package "@ngxs-labs/entity-state" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0 || ^7.0.0" (extended), would install "9.1.12").```

Could you please update it?

**Comment by aWeinzierl** [comment]
Even Angular 8 seems blocked ...

**Comment by JanMalch** [comment]
Just released v0.1.0
Please let me know if there are any errors
