### ISSUE TITLE
could not get librabry folder in my project

### ISSUE THREAD

**Issue by shantanugupta135** [ngxs-labs/entity-state#287]
Hello I tried "npm i @ngxs-labs/entity-state" to run it, it downloads all the dependencies but 'src' folder did not create which contains all library methods. Please let me know how can I get that?

**Comment by JanMalch** [comment]
What do you need it for? The original src folder is never included.

**Comment by shantanugupta135** [comment]
Could you share me a sample project how we will do Api intergration by using this package?

**Comment by JanMalch** [comment]
You can check out the integration folder for a small to-do list, which is also used for the tests.
There are no examples for integration with a REST-API. Maybe you can find tips in the ngxs docs, articles or slack channels, on how to combine ngxs with a REST-API.
