### ISSUE TITLE
Adding Api Response to Entities

### ISSUE THREAD

**Issue by shantanugupta135** [ngxs-labs/entity-state#291]
I am getting an array from Get Api call but I am unable to add them in the entities attribute, How can I add in that attribute please let me know?

**Comment by JanMalch** [comment]
Both the `Add` and the `CreateOrReplace` action accept a single entity or an array of entities.

**Comment by shantanugupta135** [comment]
Could you please send me the demo or any sample code to refer that?

**Comment by JanMalch** [comment]
The integration test shows it here: [app.component.ts#L162-L175](https://github.com/ngxs-labs/entity-state/blob/master/integration/app/app.component.ts#L162-L175).

The library doesn't provide or recommend any particular way on how to combine the app state with your API.
