### ISSUE TITLE
Compatibility with NgxsModule's developmentMode

### ISSUE THREAD

**Issue by kuhnroyal** [ngxs-labs/entity-state#52]
When I set `developmentMode: true` I get an `object is not extensible` error at https://github.com/ngxs-labs/entity-state/blob/master/src/lib/entity-state.ts#L451

Is that the expected behavior or am I doing something wrong?

**Comment by JanMalch** [comment]
What does `IFoo` look like=

**Comment by kuhnroyal** [comment]
It doesn't really matter, some interface with a `id: string` and whatever else you want to add.
The problem occurs when an entity gets added to the `entities` HashMap after `EntityState.add` is invoked.

It would be good if there were some alpha/beta releases on NPM, didn't manage to add this stackblitz atm.

**Comment by JanMalch** [comment]
`developmentMode` recursively freezes the state. While the state after every action should be a new one, the action handlers use mutability while applying their logic. This is my guess.
I will look into it.

**Comment by kuhnroyal** [comment]
@JanMalch This is fixed with https://github.com/ngxs-labs/entity-state/issues/98?

**Comment by JanMalch** [comment]
It will be, as soon as the `refactor/immutability` branch is merged. It was planned to develop the the entity state operators (#85) in there aswell. But I will create a PR for the branch now and open a new one for state operators.

**Comment by matodrobec** [comment]
Hello @JanMalch , 
Can you update npm "@ngxs-labs/entity-state". I am getting the error.

Thank you
