### ISSUE TITLE
feat: entity base class 

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/entity-state#6]
Moved from https://github.com/ngxs/store/pull/321

A base class that you can implement to get methods on your state class to simplify handling crud operations.

It looks something like this.

```TS
class Project {
  id: string;
  name: string;
}

class AddOne {
  static readonly type = '[Project] AddProject';
  constructor(public project: Project) {}
}

class AddMany {
  static readonly type = '[Project] AddProjects';
  constructor(public projects: Project[]) {}
}

interface ProjectStateModel extends EntityState<Project> {}

@State<ProjectStateModel>({
  name: 'projects',
  defaults: {
    ...EntityBase.defaults
  }
})
class ProjectState extends EntityBase<Project, ProjectStateModel> {
  // pass injector to base class so that we can get and set state
  // @todo, can we work around this?
  constructor(injector: Injector) {
    super(injector);
  }

  // will automatically do a ctx.setState if needed
  @Action(AddOne)
  addProject(ctx: StateContext<ProjectStateModel>, action: AddOne) {
    this.addOne(action.project);
  }

  @Action(AddMany)
  addProjects(ctx: StateContext<ProjectStateModel>, action: AddMany) {
    this.addMany(action.projects);
  }
}
```

for now I've only implemented these two, but it shouldn't take me too long to implement the rest of the methods.

Though I would like some input on the api of it.

I would like to be able to get at the `StateContext` from within the class.
At the moment I'm hacking it by getting `this.constructor[META_KEY]` and then calling `.next` on the stateStream.

Please let me know what you think, and if you have any suggestions to improve it even further :)

**Comment by markwhitfeld** [comment]
Closing this old approach in favor of the new...
