### ISSUE TITLE
Not working developmentMode, getting ERROR TypeError: Cannot add property VALUE_OF_ID, object is not extensible

### ISSUE THREAD

**Issue by philly-vanilly** [ngxs-labs/entity-state#98]
Steps to reproduce: set

```
    NgxsModule.forRoot(states, {
      developmentMode: true
    }),
```

in the example project and you will get

```
ERROR TypeError: Cannot add property VALUE_OF_ID, object is not extensible
    at entity-state.ts:471
```
(if you use AddOrReplace action), eg at `entities[id] = entity;`

It would be nice to have an error message suggesting to disable development mode if entity doesn't work with immutability (?)

**Comment by JanMalch** [comment]
See #52 
Is fixed in 65f2d55
